package org.openrndr.kinect2

import java.io.BufferedWriter
import java.io.File
import java.io.FileOutputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import org.slf4j.LoggerFactory

/**
 * Mesh file export utilities
 *
 * Supports exporting Mesh data to common 3D file formats:
 * - OBJ: Wavefront OBJ format (widely supported, human-readable)
 * - PLY: Stanford PLY format (efficient, supports vertex colors)
 *
 * Both formats preserve:
 * - 3D vertex positions
 * - Vertex colors (RGB)
 * - Surface normals
 * - Triangle face definitions
 */
object MeshExporter {
    private val logger = LoggerFactory.getLogger(MeshExporter::class.java)

    /**
     * Exports mesh to Wavefront OBJ format
     *
     * OBJ is a widely supported 3D format that's human-readable (ASCII).
     * It stores vertices, normals, and faces. Colors are NOT part of the OBJ standard
     * but can be stored in a companion MTL (material) file.
     *
     * Format:
     * ```
     * # Comment
     * v x y z          # Vertex position
     * vn nx ny nz      # Vertex normal
     * f v1 v2 v3       # Face (triangle)
     * ```
     *
     * @param mesh The mesh to export
     * @param filePath Output file path
     * @throws java.io.IOException If file write fails
     */
    fun exportToOBJ(mesh: Mesh, filePath: String) {
        val startTime = System.currentTimeMillis()
        val file = File(filePath)

        file.bufferedWriter().use { writer ->
            // Header
            writer.write("# Kinect V2 Mesh Export\n")
            writer.write("# Generated by Kinect-OPENRNDR\n")
            writer.write("# Vertices: ${mesh.vertexCount}\n")
            writer.write("# Triangles: ${mesh.triangleCount}\n")
            writer.write("\n")

            // Write vertices
            writer.write("# Vertex positions\n")
            for (vertex in mesh.vertices) {
                val p = vertex.position
                writer.write("v ${p.x} ${p.y} ${p.z}\n")
            }
            writer.write("\n")

            // Write normals
            writer.write("# Vertex normals\n")
            for (vertex in mesh.vertices) {
                val n = vertex.normal
                writer.write("vn ${n.x} ${n.y} ${n.z}\n")
            }
            writer.write("\n")

            // Write vertex colors as comments (OBJ doesn't support colors natively)
            writer.write("# Vertex colors (not part of OBJ standard)\n")
            for ((idx, vertex) in mesh.vertices.withIndex()) {
                val c = vertex.color
                writer.write("# vc ${idx + 1} ${c.r} ${c.g} ${c.b}\n")
            }
            writer.write("\n")

            // Write faces (triangles)
            // OBJ indices are 1-based
            writer.write("# Faces (triangles)\n")
            for (i in mesh.indices.indices step 3) {
                val i1 = mesh.indices[i] + 1
                val i2 = mesh.indices[i + 1] + 1
                val i3 = mesh.indices[i + 2] + 1
                // Format: f v1//vn1 v2//vn2 v3//vn3 (vertex//normal, no texture coords)
                writer.write("f $i1//$i1 $i2//$i2 $i3//$i3\n")
            }
        }

        val elapsed = System.currentTimeMillis() - startTime
        logger.info("Exported OBJ mesh to $filePath (${mesh.vertexCount} vertices, ${mesh.triangleCount} triangles) in ${elapsed}ms")
    }

    /**
     * Exports mesh to Stanford PLY format (ASCII variant)
     *
     * PLY is an efficient 3D format that natively supports vertex colors.
     * This implementation uses the ASCII variant for simplicity and readability.
     * (Binary PLY would be more compact but requires more complex encoding)
     *
     * Format:
     * ```
     * ply
     * format ascii 1.0
     * element vertex N
     * property float x
     * property float y
     * property float z
     * property float nx
     * property float ny
     * property float nz
     * property uchar red
     * property uchar green
     * property uchar blue
     * element face M
     * property list uchar int vertex_indices
     * end_header
     * <vertex data>
     * <face data>
     * ```
     *
     * @param mesh The mesh to export
     * @param filePath Output file path
     * @param binary If true, use binary format (more compact); if false, use ASCII (default)
     * @throws java.io.IOException If file write fails
     */
    fun exportToPLY(mesh: Mesh, filePath: String, binary: Boolean = false) {
        if (binary) {
            exportToPLYBinary(mesh, filePath)
        } else {
            exportToPLYAscii(mesh, filePath)
        }
    }

    /**
     * Exports mesh to ASCII PLY format
     */
    private fun exportToPLYAscii(mesh: Mesh, filePath: String) {
        val startTime = System.currentTimeMillis()
        val file = File(filePath)

        file.bufferedWriter().use { writer ->
            // PLY header
            writer.write("ply\n")
            writer.write("format ascii 1.0\n")
            writer.write("comment Kinect V2 Mesh Export\n")
            writer.write("comment Generated by Kinect-OPENRNDR\n")

            // Vertex element
            writer.write("element vertex ${mesh.vertexCount}\n")
            writer.write("property float x\n")
            writer.write("property float y\n")
            writer.write("property float z\n")
            writer.write("property float nx\n")
            writer.write("property float ny\n")
            writer.write("property float nz\n")
            writer.write("property uchar red\n")
            writer.write("property uchar green\n")
            writer.write("property uchar blue\n")

            // Face element
            writer.write("element face ${mesh.triangleCount}\n")
            writer.write("property list uchar int vertex_indices\n")

            writer.write("end_header\n")

            // Write vertex data
            for (vertex in mesh.vertices) {
                val p = vertex.position
                val n = vertex.normal
                val c = vertex.color

                // Convert colors from [0,1] to [0,255]
                val r = (c.r * 255).toInt().coerceIn(0, 255)
                val g = (c.g * 255).toInt().coerceIn(0, 255)
                val b = (c.b * 255).toInt().coerceIn(0, 255)

                writer.write("${p.x} ${p.y} ${p.z} ${n.x} ${n.y} ${n.z} $r $g $b\n")
            }

            // Write face data
            for (i in mesh.indices.indices step 3) {
                val i1 = mesh.indices[i]
                val i2 = mesh.indices[i + 1]
                val i3 = mesh.indices[i + 2]
                writer.write("3 $i1 $i2 $i3\n")
            }
        }

        val elapsed = System.currentTimeMillis() - startTime
        logger.info("Exported PLY (ASCII) mesh to $filePath (${mesh.vertexCount} vertices, ${mesh.triangleCount} triangles) in ${elapsed}ms")
    }

    /**
     * Exports mesh to binary PLY format (more compact)
     */
    private fun exportToPLYBinary(mesh: Mesh, filePath: String) {
        val startTime = System.currentTimeMillis()
        val file = File(filePath)

        FileOutputStream(file).use { fos ->
            // Write ASCII header
            val header = buildString {
                append("ply\n")
                append("format binary_little_endian 1.0\n")
                append("comment Kinect V2 Mesh Export\n")
                append("comment Generated by Kinect-OPENRNDR\n")
                append("element vertex ${mesh.vertexCount}\n")
                append("property float x\n")
                append("property float y\n")
                append("property float z\n")
                append("property float nx\n")
                append("property float ny\n")
                append("property float nz\n")
                append("property uchar red\n")
                append("property uchar green\n")
                append("property uchar blue\n")
                append("element face ${mesh.triangleCount}\n")
                append("property list uchar int vertex_indices\n")
                append("end_header\n")
            }
            fos.write(header.toByteArray(Charsets.US_ASCII))

            // Allocate buffer for binary data
            val vertexSize = 6 * 4 + 3  // 6 floats + 3 bytes (RGB)
            val vertexBuffer = ByteBuffer.allocate(mesh.vertexCount * vertexSize)
            vertexBuffer.order(ByteOrder.LITTLE_ENDIAN)

            // Write vertex data (binary)
            for (vertex in mesh.vertices) {
                val p = vertex.position
                val n = vertex.normal
                val c = vertex.color

                // Position (3 floats)
                vertexBuffer.putFloat(p.x.toFloat())
                vertexBuffer.putFloat(p.y.toFloat())
                vertexBuffer.putFloat(p.z.toFloat())

                // Normal (3 floats)
                vertexBuffer.putFloat(n.x.toFloat())
                vertexBuffer.putFloat(n.y.toFloat())
                vertexBuffer.putFloat(n.z.toFloat())

                // Color (3 bytes)
                vertexBuffer.put((c.r * 255).toInt().coerceIn(0, 255).toByte())
                vertexBuffer.put((c.g * 255).toInt().coerceIn(0, 255).toByte())
                vertexBuffer.put((c.b * 255).toInt().coerceIn(0, 255).toByte())
            }

            fos.write(vertexBuffer.array())

            // Write face data (binary)
            val faceSize = 1 + 3 * 4  // 1 byte (count) + 3 ints (indices)
            val faceBuffer = ByteBuffer.allocate(mesh.triangleCount * faceSize)
            faceBuffer.order(ByteOrder.LITTLE_ENDIAN)

            for (i in mesh.indices.indices step 3) {
                faceBuffer.put(3.toByte())  // Triangle has 3 vertices
                faceBuffer.putInt(mesh.indices[i])
                faceBuffer.putInt(mesh.indices[i + 1])
                faceBuffer.putInt(mesh.indices[i + 2])
            }

            fos.write(faceBuffer.array())
        }

        val elapsed = System.currentTimeMillis() - startTime
        logger.info("Exported PLY (binary) mesh to $filePath (${mesh.vertexCount} vertices, ${mesh.triangleCount} triangles) in ${elapsed}ms")
    }

    /**
     * Exports mesh to STL format (for 3D printing)
     *
     * STL (STereoLithography) is the standard format for 3D printing.
     * It stores only triangle geometry (no colors, no normals per-vertex).
     * This implementation uses the ASCII variant.
     *
     * Note: STL does NOT support vertex colors. Use PLY if you need colors.
     *
     * Format:
     * ```
     * solid name
     * facet normal nx ny nz
     *   outer loop
     *     vertex x1 y1 z1
     *     vertex x2 y2 z2
     *     vertex x3 y3 z3
     *   endloop
     * endfacet
     * endsolid name
     * ```
     *
     * @param mesh The mesh to export
     * @param filePath Output file path
     * @throws java.io.IOException If file write fails
     */
    fun exportToSTL(mesh: Mesh, filePath: String) {
        val startTime = System.currentTimeMillis()
        val file = File(filePath)

        file.bufferedWriter().use { writer ->
            writer.write("solid kinect_mesh\n")

            // Write each triangle
            for (i in mesh.indices.indices step 3) {
                val v1 = mesh.vertices[mesh.indices[i]]
                val v2 = mesh.vertices[mesh.indices[i + 1]]
                val v3 = mesh.vertices[mesh.indices[i + 2]]

                // Compute face normal (cross product)
                val edge1 = v2.position - v1.position
                val edge2 = v3.position - v1.position
                val normal = edge1.cross(edge2).normalized

                writer.write("  facet normal ${normal.x} ${normal.y} ${normal.z}\n")
                writer.write("    outer loop\n")
                writer.write("      vertex ${v1.position.x} ${v1.position.y} ${v1.position.z}\n")
                writer.write("      vertex ${v2.position.x} ${v2.position.y} ${v2.position.z}\n")
                writer.write("      vertex ${v3.position.x} ${v3.position.y} ${v3.position.z}\n")
                writer.write("    endloop\n")
                writer.write("  endfacet\n")
            }

            writer.write("endsolid kinect_mesh\n")
        }

        val elapsed = System.currentTimeMillis() - startTime
        logger.info("Exported STL mesh to $filePath (${mesh.triangleCount} triangles) in ${elapsed}ms")
    }
}
